spring:
  application:
    name: T1-Debut
  datasource:
    url: jdbc:postgresql://localhost:5432/Debut
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS public
      connection-timeout: 10000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update # или другой режим, если это необходимо

api-logging:
  http:
    level: INFO
    format: TEXT

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
    example:
      aop:
        aspect:
          LoggingAspect: DEBUG
    hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
